#' Mutability characteristic. Searches interval with the maximum growth rate in the \strong{time.window}
#' and backtraces hypothetical resistant population.
#' @param tables - List of tables generated by \emph{calaculate_tables} function.
#' @param tables.gr - List of tables generated by \emph{growth.rates} function.
#' @param tables.cum - List of tables generated by \emph{cumulative}
#' @param time.window - A vector that specifies interval where a point with maximum growth rate will initiate
#' backtracing of a hypothetical population.
#' @param MIC - Minimum Inhibitory Concentration.
#' @param Dtime - Dilution time.
#' @param PPower - A power of peristaltic pumps. Default = 100.
#' @param V - Volume of of media in the reactors. Default = 20.

#' @export

mutability = function(tables, tables.gr, tables.col, tables.cum, time.window = c(25,50), tube = "Tube1", MIC = 0.004, Dtime = 8, PPower = 100, lt = 0.15, V = 20){
  #time.start = which(tables.gr[[tube]]$growth.rate == max.gr)
  right.side.window = tail(which(tables.gr[[tube]]$time <= time.window[2]), 1)  	#position of the right side of the time window in table.gr

  #find the start of the previous wave
  times.pump2 = which(tables.col[[tube]]$OD$pump[1:right.side.window] == "Pump2")	#position of times when pump2 was actiated
  d.time = times.pump2 - c(0,times.pump2[-length(times.pump2)])                     #difference between two subsequent times when pump2 was activated
  time.thr = times.pump2[tail(which(d.time > 1), 2)[1]]                             #start of the pump2 work on the previous peak
  time.start = times.pump2[tail(which(d.time > 1), 1)]                              #start of the pump2 work on the current peak. We will lead our mutated population from here.
#  gr = tables.gr[[tube]]$growth.rate[time.start]                                	#growth rate at the starting point 
  
  #outliers removal from growth rates
  tgr.temp = tables.gr[[tube]]$growth.rate[tables.gr[[tube]]$time >= time.window[1] & tables.gr[[tube]]$time <= time.window[2]]
  tgr.temp.quant = quantile(tgr.temp, probs=c(.25, .75))
  tgr.temp.iqr = 1.5 * IQR(tgr.temp)
  tgr.temp[tgr.temp < (tgr.temp.quant[1] - tgr.temp.iqr)] = median(tgr.temp)
  tgr.temp[tgr.temp > (tgr.temp.quant[2] + tgr.temp.iqr)] = median(tgr.temp)
  gr = max(tgr.temp)
  
  mutated.OD = tables.col[[tube]]$OD$value[time.start]                              #OD of the mutated populatin in the start
  dV.temp = data.frame(time.mut = tables.col[[tube]]$OD$time[time.start], value.mut = mutated.OD)     #data frame of the time (sec) and mutated.OD

  OD.start = tables.col[[tube]]$OD$value[time.start] / exp( tables.gr[[tube]]$growth.rate[time.start] * (tables.col[[tube]]$OD$time[time.start]/3600 - tables.gr[[tube]]$t.start[time.start]))
  OD.prev.stop = tables.col[[tube]]$OD$value[time.start - 1] * exp( tables.gr[[tube]]$growth.rate[time.start - 1] * (tables.gr[[tube]]$t.stop[time.start-1] - tables.col[[tube]]$OD$time[time.start - 1]/3600))

  dil.rate = OD.start/OD.prev.stop
  dil.rate.fix = 1 - 0.003 * Dtime * PPower / V
  
  #dV1 = data.frame(time.mut = tables.col[[tube]]$OD$time[time.start], value.mut = mutated.OD, dil = c(0), tinter = c(), time.mut.mone = tables.col[[tube]]$OD$time[time.start-1])

  while( time.start >= time.thr ){
  	if(dil.rate > 1 || OD.prev.stop < lt || dil.rate < 0.8 * dil.rate.fix){
      dil.rate = dil.rate.fix
    }
    
    t.inter = (tables.gr[[tube]]$t.stop[time.start-1] + tables.gr[[tube]]$t.start[time.start]) / 2
    
    mutated.OD1 = mutated.OD / exp( gr  * (tables.gr[[tube]]$time[time.start] - t.inter ) ) / dil.rate #mutated OD on the beginning of the inerval
    mutated.OD1 = mutated.OD1 / exp( gr * (t.inter - tables.gr[[tube]]$time[time.start - 1] ) ) #mutated OD on the middle of the previous inerval
    
    if( mutated.OD1 > tables.col[[tube]]$OD$value[time.start - 1] ){
    	mutated.OD1 = mutated.OD / exp( tables.gr[[tube]]$growth.rate[time.start-1]  * (tables.gr[[tube]]$time[time.start] - t.inter ) ) / dil.rate #mutated OD on the beginning of the inerval
    	mutated.OD1 = mutated.OD1 / exp( tables.gr[[tube]]$growth.rate[time.start-1] * (t.inter - tables.gr[[tube]]$time[time.start - 1] ) ) #mutated OD on the middle of the previous inerval
    }
    
    mutated.OD = mutated.OD1
    
    time.start = time.start - 1   #step back one interval
    dV.temp = rbind(dV.temp,data.frame(time.mut = tables.col[[tube]]$OD$time[time.start], value.mut = mutated.OD))
    #dV1 = rbind(dV1,data.frame(time.mut = tables.col[[tube]]$OD$time[time.start], value.mut = mutated.OD, dil = dil.rate, tinter = t.inter * 3600, time.mut.mone = tables.gr[[tube]]$time[time.start-1]*3600))
    OD.start = tables.col[[tube]]$OD$value[time.start] / exp( tables.gr[[tube]]$growth.rate[time.start] * (tables.col[[tube]]$OD$time[time.start]/3600 - tables.gr$Tube1$t.start[time.start]))
    OD.prev.stop = tables.col[[tube]]$OD$value[time.start - 1] * exp( tables.gr[[tube]]$growth.rate[time.start - 1] * (tables.gr$Tube1$t.stop[time.start-1] - tables.col[[tube]]$OD$time[time.start - 1]/3600))
    dil.rate = OD.start/OD.prev.stop
  }
  
  time.convergence = time.start
  t.inter = (tables.gr[[tube]]$t.stop[time.start-1] + tables.gr[[tube]]$t.start[time.start]) / 2
  mutated.OD2 = mutated.OD / exp( gr  * (tables.gr[[tube]]$time[time.start] - t.inter ) ) / dil.rate #mutated OD on the beginning of the inerval
  dOD.zero.temp = mutated.OD - mutated.OD2
  time.start = time.start - 1
  mutated.OD = mutated.OD2
  
  while( time.start > 1 ){
  	if(dil.rate > 1 || OD.prev.stop < lt || dil.rate < 0.8 * dil.rate.fix){
      dil.rate = dil.rate.fix
    }
    
    t.inter2 = (tables.gr[[tube]]$t.stop[time.start-1] + tables.gr[[tube]]$t.start[time.start]) / 2
    
    mutated.OD2 = mutated.OD / exp( gr  * (t.inter - t.inter2 ) )  #mutated OD on the beginning of the inerval
    dOD.zero.temp = dOD.zero.temp + (mutated.OD - mutated.OD2)
    mutated.OD = mutated.OD2 / dil.rate
    
    time.start = time.start - 1   #step back one interval
    OD.start = tables.col[[tube]]$OD$value[time.start] / exp( tables.gr[[tube]]$growth.rate[time.start] * (tables.col[[tube]]$OD$time[time.start]/3600 - tables.gr$Tube1$t.start[time.start]))
    OD.prev.stop = tables.col[[tube]]$OD$value[time.start - 1] * exp( tables.gr[[tube]]$growth.rate[time.start - 1] * (tables.gr$Tube1$t.stop[time.start-1] - tables.col[[tube]]$OD$time[time.start - 1]/3600))
    dil.rate = OD.start/OD.prev.stop
  }
  
  dOD.zero.temp = dOD.zero.temp + mutated.OD2

  #mut.prob = 1/tables.cum[[tube]]$OD$N.rep.events[time.convergence-1]
  mut.prob = dOD.zero.temp/tables.cum[[tube]]$OD$value[time.convergence]
  list.temp = list(tube = tables.col[[tube]])
  names(list.temp) = tube
  draw(list.temp,  MIC = MIC, add.model = T, model.table = dV.temp, m.prob = mut.prob)
}