#' Write tables to file. Each reactor will have it's own files.
#' @param tables - List of tables generated by \emph{calaculate_tables} function.
#' @param united - If TRUE creates the united table (*_United.txt) for OD and Concentration.
#' @param col - If TRUE the input table is collapsed
#' If FALSE - files for the tables of OD and Concetration changes will be created separately (*_OD.txt, *_Conc.txt)

#' @export

write.m.tables <- function(tables, united = F, col = F){
  #united == T - create united table of time, OD and concentration
  if( col == F ){
    for(i in 1:length(tables)){
      tV <- tables[i][[1]][1]$OD
      tC <- tables[i][[1]][2]$Conc
      tube <- names(tables)[i]
      
      if(united == T){
        tU <- tV    #create united OD-Concentration table
        cbind(tU,data.frame(concentration = rep(0,dim(tV)[1])))
        tU$concentration[tU$time < tC$time[1]] = C0
        tU$concentration[tU$time < tC$time[dim(tC)[1]]] = tC$Concentration[dim(tC)[1]]
        
        for(j in 1:dim(tC)[1]){
          tU$concentration[tU$time > tC$time[j] & tU$time < tC$time[j+1]] = tC$Concentration[i]
        }
        
        write.table(x = tU, file = paste0(tube,"_United.txt"), sep = "\t", quote = F, row.names = F)
      }else{
      	write.table(x = tV, file = paste0(tube,"_OD.txt"), sep = "\t", quote = F, row.names = F)
      	write.table(x = tC, file = paste0(tube,"_Conc.txt"), sep = "\t", quote = F, row.names = F)
      }
    }
  }else{
      for(i in 1:length(tables)){
        tV <- tables[i][[1]][1]$OD
        tC <- tables[i][[1]][2]$Conc
        tube <- names(tables)[i]
        
        if(united == T){
          tU <- tV    #create united OD-Concentration table
          cbind(tU,data.frame(concentration = rep(0,dim(tV)[1])))
          tU$concentration = round(tC$Concentration, 2)
          
          write.table(x = tU, file = paste0(tube,"_United.txt"), sep = "\t", quote = F, row.names = F)
        }else{
          write.table(x = tV, file = paste0(tube,"_OD.txt"), sep = "\t", quote = F, row.names = F)
          write.table(x = tC, file = paste0(tube,"_Conc.txt"), sep = "\t", quote = F, row.names = F)
        }
    }
  }
}